// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type Order struct {
	ID         uuid.UUID
	CreatedAt  time.Time
	UpdatedAt  time.Time
	UserID     uuid.UUID
	Status     string
	TotalItems int32
}

type OrderItem struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ProductID uuid.UUID
	OrderID   uuid.UUID
	Quantity  int32
	Price     int32
}

type Payment struct {
	ID          uuid.UUID
	OrderID     uuid.UUID
	ExternalID  uuid.UUID
	Method      string
	Acquirer    string
	Currency    string
	Status      string
	FraudStatus string
	Amount      int32
	QrString    string
	UrlImage    string
	Payload     pqtype.NullRawMessage
	ExpireAt    sql.NullTime
	PaidAt      sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type Product struct {
	ID            uuid.UUID
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Name          string
	Price         int32
	Category      string
	Stock         int32
	Description   string
	StockReserved int32
	Features      pqtype.NullRawMessage
}

type RefreshToken struct {
	Token     string
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Name           string
	Email          string
	HashedPassword string
	Provider       string
}
