// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, created_at, updated_at, user_id, status, total_items)
VALUES(
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3
)
RETURNING id, created_at, updated_at, user_id, status, total_items
`

type CreateOrderParams struct {
	UserID     uuid.UUID
	Status     string
	TotalItems int32
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.UserID, arg.Status, arg.TotalItems)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.Status,
		&i.TotalItems,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, user_id, total_items FROM orders WHERE id = $1
`

type GetOrderByIDRow struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TotalItems int32
}

func (q *Queries) GetOrderByID(ctx context.Context, id uuid.UUID) (GetOrderByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(&i.ID, &i.UserID, &i.TotalItems)
	return i, err
}

const updateStatusOrder = `-- name: UpdateStatusOrder :exec
UPDATE orders
SET status = $1
WHERE id = $2
`

type UpdateStatusOrderParams struct {
	Status string
	ID     uuid.UUID
}

func (q *Queries) UpdateStatusOrder(ctx context.Context, arg UpdateStatusOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateStatusOrder, arg.Status, arg.ID)
	return err
}
