// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order_items.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createOrderItems = `-- name: CreateOrderItems :one
INSERT INTO order_items (id, created_at, updated_at, product_id, order_id, quantity, price)
VALUES(
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3,
  $4
)
RETURNING id, created_at, updated_at, product_id, order_id, quantity, price
`

type CreateOrderItemsParams struct {
	ProductID uuid.UUID
	OrderID   uuid.UUID
	Quantity  int32
	Price     int32
}

func (q *Queries) CreateOrderItems(ctx context.Context, arg CreateOrderItemsParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItems,
		arg.ProductID,
		arg.OrderID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductID,
		&i.OrderID,
		&i.Quantity,
		&i.Price,
	)
	return i, err
}
