// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (
  id, 
  order_id, 
  external_id, 

  method, 
  acquirer, 
  currency, 

  status, 
  fraud_status,
  amount,

  qr_string,
  url_image,

  payload,
  
  expire_at,
  paid_at,
  created_at,
  updated_at
  )
VALUES(
  gen_random_uuid(),
  $1,
  $2,

  $3,
  $4,
  $5,

  $6,
  $7,
  $8,

  $9,
  $10,

  $11,
  
  $12,
  $13,
  NOW(),
  NOW()
)
RETURNING id, order_id, external_id, method, acquirer, currency, status, fraud_status, amount, qr_string, url_image, payload, expire_at, paid_at, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID     uuid.UUID
	ExternalID  uuid.UUID
	Method      string
	Acquirer    string
	Currency    string
	Status      string
	FraudStatus string
	Amount      int32
	QrString    string
	UrlImage    string
	Payload     pqtype.NullRawMessage
	ExpireAt    sql.NullTime
	PaidAt      sql.NullTime
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.OrderID,
		arg.ExternalID,
		arg.Method,
		arg.Acquirer,
		arg.Currency,
		arg.Status,
		arg.FraudStatus,
		arg.Amount,
		arg.QrString,
		arg.UrlImage,
		arg.Payload,
		arg.ExpireAt,
		arg.PaidAt,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ExternalID,
		&i.Method,
		&i.Acquirer,
		&i.Currency,
		&i.Status,
		&i.FraudStatus,
		&i.Amount,
		&i.QrString,
		&i.UrlImage,
		&i.Payload,
		&i.ExpireAt,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentById = `-- name: GetPaymentById :one
SELECT qr_string, url_image, expire_at FROM payments WHERE order_id = $1
`

type GetPaymentByIdRow struct {
	QrString string
	UrlImage string
	ExpireAt sql.NullTime
}

func (q *Queries) GetPaymentById(ctx context.Context, orderID uuid.UUID) (GetPaymentByIdRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentById, orderID)
	var i GetPaymentByIdRow
	err := row.Scan(&i.QrString, &i.UrlImage, &i.ExpireAt)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :exec
UPDATE payments 
SET status = $2, paid_at = $3
WHERE order_id = $1
`

type UpdatePaymentParams struct {
	OrderID uuid.UUID
	Status  string
	PaidAt  sql.NullTime
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error {
	_, err := q.db.ExecContext(ctx, updatePayment, arg.OrderID, arg.Status, arg.PaidAt)
	return err
}
