// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (id, created_at, updated_at, name, price, category, stock, description)
VALUES(
  gen_random_uuid(),
  NOW(),
  NOW(),
  $1,
  $2,
  $3,
  $4,
  $5
)
RETURNING id, created_at, updated_at, name, price, category, stock, description
`

type CreateProductParams struct {
	Name        string
	Price       int32
	Category    string
	Stock       int32
	Description string
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.Price,
		arg.Category,
		arg.Stock,
		arg.Description,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Price,
		&i.Category,
		&i.Stock,
		&i.Description,
	)
	return i, err
}

const getAllPrice = `-- name: GetAllPrice :many
SELECT id, price, stock, name FROM products ORDER BY created_at ASC
`

type GetAllPriceRow struct {
	ID    uuid.UUID
	Price int32
	Stock int32
	Name  string
}

func (q *Queries) GetAllPrice(ctx context.Context) ([]GetAllPriceRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllPrice)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPriceRow
	for rows.Next() {
		var i GetAllPriceRow
		if err := rows.Scan(
			&i.ID,
			&i.Price,
			&i.Stock,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProduct = `-- name: GetAllProduct :many
SELECT id, created_at, updated_at, name, price, category, stock, description FROM products
WHERE 
  (name ILIKE '%' || $1::text || '%' OR $1::text = '') 
  AND (category = $2::text OR $2::text ='')
ORDER BY created_at ASC
LIMIT $4::int
OFFSET $3::int
`

type GetAllProductParams struct {
	Name      string
	Category  string
	OffsetVal int32
	LimitVal  int32
}

func (q *Queries) GetAllProduct(ctx context.Context, arg GetAllProductParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, getAllProduct,
		arg.Name,
		arg.Category,
		arg.OffsetVal,
		arg.LimitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Price,
			&i.Category,
			&i.Stock,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, created_at, updated_at, name, price, category, stock, description FROM products WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetProduct(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Price,
		&i.Category,
		&i.Stock,
		&i.Description,
	)
	return i, err
}

const updateProduct = `-- name: UpdateProduct :many
UPDATE products
SET stock = stock - order_items.quantity
FROM order_items
WHERE order_items.order_id = $1 
AND order_items.product_id = products.id
AND stock >= order_items.quantity
RETURNING order_items.id, order_items.created_at, order_items.updated_at, product_id, order_id, quantity, order_items.price, products.id, products.created_at, products.updated_at, name, products.price, category, stock, description
`

type UpdateProductRow struct {
	ID          uuid.UUID
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ProductID   uuid.UUID
	OrderID     uuid.UUID
	Quantity    int32
	Price       int32
	ID_2        uuid.UUID
	CreatedAt_2 time.Time
	UpdatedAt_2 time.Time
	Name        string
	Price_2     int32
	Category    string
	Stock       int32
	Description string
}

func (q *Queries) UpdateProduct(ctx context.Context, orderID uuid.UUID) ([]UpdateProductRow, error) {
	rows, err := q.db.QueryContext(ctx, updateProduct, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpdateProductRow
	for rows.Next() {
		var i UpdateProductRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductID,
			&i.OrderID,
			&i.Quantity,
			&i.Price,
			&i.ID_2,
			&i.CreatedAt_2,
			&i.UpdatedAt_2,
			&i.Name,
			&i.Price_2,
			&i.Category,
			&i.Stock,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
